# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enviro_v3.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.prog_reduc = QtWidgets.QProgressBar(self.centralwidget)
        self.prog_reduc.setGeometry(QtCore.QRect(190, 390, 251, 23))
        self.prog_reduc.setMaximum(1000)
        self.prog_reduc.setProperty("value", 0)
        self.prog_reduc.setTextVisible(True)
        self.prog_reduc.setObjectName("prog_reduc")
        self.prog_ox = QtWidgets.QProgressBar(self.centralwidget)
        self.prog_ox.setGeometry(QtCore.QRect(190, 440, 251, 23))
        self.prog_ox.setMaximum(10)
        self.prog_ox.setProperty("value", 0)
        self.prog_ox.setTextVisible(True)
        self.prog_ox.setOrientation(QtCore.Qt.Horizontal)
        self.prog_ox.setObjectName("prog_ox")
        self.prog_nh3 = QtWidgets.QProgressBar(self.centralwidget)
        self.prog_nh3.setGeometry(QtCore.QRect(190, 490, 251, 23))
        self.prog_nh3.setMaximum(300)
        self.prog_nh3.setProperty("value", 0)
        self.prog_nh3.setTextVisible(True)
        self.prog_nh3.setObjectName("prog_nh3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 390, 111, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 440, 111, 19))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 490, 111, 19))
        self.label_3.setObjectName("label_3")
        self.lcd_temp = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_temp.setGeometry(QtCore.QRect(130, 40, 101, 41))
        self.lcd_temp.setObjectName("lcd_temp")
        self.lcd_hum = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_hum.setGeometry(QtCore.QRect(130, 120, 101, 41))
        self.lcd_hum.setObjectName("lcd_hum")
        self.lcd_pres = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_pres.setGeometry(QtCore.QRect(130, 200, 101, 41))
        self.lcd_pres.setObjectName("lcd_pres")
        self.lcd_lum = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_lum.setGeometry(QtCore.QRect(130, 280, 101, 41))
        self.lcd_lum.setObjectName("lcd_lum")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 50, 91, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 130, 81, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 210, 61, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(17, 290, 91, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(240, 50, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(240, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(240, 210, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(240, 290, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setObjectName("label_11")
        self.btn_rec = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rec.setGeometry(QtCore.QRect(550, 460, 131, 34))
        self.btn_rec.setObjectName("btn_rec")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(540, 420, 151, 31))
        self.label_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(580, 130, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setTextFormat(QtCore.Qt.AutoText)
        self.label_13.setObjectName("label_13")
        self.lcd_pm1_0 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_pm1_0.setGeometry(QtCore.QRect(470, 120, 101, 41))
        self.lcd_pm1_0.setObjectName("lcd_pm1_0")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(580, 190, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setTextFormat(QtCore.Qt.AutoText)
        self.label_14.setObjectName("label_14")
        self.lcd_pm2_5 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_pm2_5.setGeometry(QtCore.QRect(470, 180, 101, 41))
        self.lcd_pm2_5.setObjectName("lcd_pm2_5")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(580, 250, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setTextFormat(QtCore.Qt.AutoText)
        self.label_15.setObjectName("label_15")
        self.lcd_pm10 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_pm10.setGeometry(QtCore.QRect(470, 240, 101, 41))
        self.lcd_pm10.setObjectName("lcd_pm10")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 31))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtWidgets.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuitter = QtWidgets.QAction(MainWindow)
        self.actionQuitter.setObjectName("actionQuitter")
        self.menuFichier.addAction(self.actionQuitter)
        self.menubar.addAction(self.menuFichier.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mesurer son environnement"))
        self.prog_reduc.setFormat(_translate("MainWindow", "%v ppm"))
        self.prog_ox.setFormat(_translate("MainWindow", "%v ppm"))
        self.prog_nh3.setFormat(_translate("MainWindow", "%v ppm"))
        self.label.setText(_translate("MainWindow", "Gaz Réducteur"))
        self.label_2.setText(_translate("MainWindow", "Gaz oxydant"))
        self.label_3.setText(_translate("MainWindow", "Ammoniaque"))
        self.label_4.setText(_translate("MainWindow", "Température"))
        self.label_5.setText(_translate("MainWindow", "Humidité"))
        self.label_6.setText(_translate("MainWindow", "Pression"))
        self.label_7.setText(_translate("MainWindow", "Luminosité"))
        self.label_8.setText(_translate("MainWindow", "°C"))
        self.label_9.setText(_translate("MainWindow", "%"))
        self.label_10.setText(_translate("MainWindow", "hPa"))
        self.label_11.setText(_translate("MainWindow", "lux"))
        self.btn_rec.setText(_translate("MainWindow", "Start recording"))
        self.label_12.setText(_translate("MainWindow", "Log on Google Sheet"))
        self.label_13.setText(_translate("MainWindow", "PM 1.0"))
        self.label_14.setText(_translate("MainWindow", "PM 2.5"))
        self.label_15.setText(_translate("MainWindow", "PM 10"))
        self.menuFichier.setTitle(_translate("MainWindow", "Fichier"))
        self.actionQuitter.setText(_translate("MainWindow", "Quitter"))

